import './globals.css';
import { ThemeProvider } from './components/ThemeContext';

export const metadata = {
  title: 'David Lucas - Portfolio',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="pt-BR">
      <body>
        <ThemeProvider>
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
