import './globals.css';
import { ThemeProvider } from './components/ThemeContext';
import { generateViewport } from './generateViewport';

export const metadata = {
  title: 'David Lucas - Portfolio',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  const viewport = generateViewport();

  return (
    <html lang="pt-BR">
      <head>
        <meta name="viewport" content={viewport.viewport} />
      </head>
      <body>
        <ThemeProvider>
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
